%YAML:1.0

#camera calibration 
model_type: PINHOLE
camera_name: gopro

#image resize factor. Note that, this factor MUST be same as OKVIS config file
resizeFactor: 1.0

#optimization parameters
max_solver_time: 0.05  # max solver itration time (ms), to guarantee real time
max_num_iterations: 20   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#loop closure 
#if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
#also give the camera calibration file same as feature_tracker node
loop_closure_params:
    enable: 1  
    min_correspondences: 25
    pnp_reprojection_threshold: 10.0               

fast_relocalization: 1

health:
    enable: 0
    min_keypoints: 15
    consecutive_keyframes: 3
    keyframe_wait_time: 2.0
    kps_per_quadrant: 1


# Added by Bharat
# Parameters for color mapping as we need to subscribe to original color image
debug_image: 0
image_height: 960
image_width: 540
distortion_coefficients: [-0.1150974141409347,  0.10292772047643643, 0.001419836324816038, -0.0018379214527896284]
focal_length: [582.7585362687838, 580.8446349178992]
principal_point: [479.95702656023155, 271.8298929212255]
