%YAML:1.0

#camera calibration 
model_type: PINHOLE
camera_name: gopro2  

#image resize factor. Note that, this factor MUST be same as OKVIS config file
resizeFactor: 1.0

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

fast_relocalization: 1

#loop closure 
#if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
#also give the camera calibration file same as feature_tracker node
loop_closure_params:
    enable: 1  
    min_correspondences: 35
    pnp_reprojection_threshold: 8.0     

health:
    enable: 0
    min_keypoints: 15
    consecutive_keyframes: 3
    keyframe_wait_time: 2.0
    kps_per_quadrant: 1

global_map_params:
    enable: 1
    min_landmark_quality: 0.001

debug_image: 1

image_height: 540
image_width: 960
focal_length: [583.16116134, 581.292988]
principal_point: [481.92859774, 270.2504108]
distortion_coefficients: [-0.10973803,  0.09313709,  0.00143941,  0.0004831]