%YAML:1.0

#camera calibration 
model_type: PINHOLE
camera_name: left

#image resize factor. Note that, this factor MUST be same as OKVIS config file
resizeFactor: 0.5

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#loop closure parameters
loop_closure: 1   #if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
                     #also give the camera calibration file same as feature_tracker node
fast_relocalization: 1
min_loop_num: 35
ransac_reproj_threshold: 10.0

image_height: 1100
image_width: 1600
focal_length: [875.8760546337106, 874.3320431510673]
principal_point: [795.6991969348003, 559.9630752248089]
distortion_coefficients: [-0.076681019896292, 0.05597074463269014, -6.58597206142547e-05,  -0.00036397743435735637]
