FROM 18r441m/ros:noetic-desktop-full

# Based on 18r441m svin dockerfile

ARG CERES_VERSION=1.14.x
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV ROS_DISTRO=noetic
ENV brisk_DIR=/usr/local/lib/CMake/brisk
ENV XDG_RUNTIME_DIR=/tmp/runtime-root

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc-10 \
    g++-10 \
    x11-apps \
    mesa-utils \
    libgl1-mesa-glx \
    build-essential \
    cmake \
    libcanberra-gtk-module \
    libcanberra-gtk3-module \
    ros-noetic-pcl-ros \
    ros-noetic-tf2-sensor-msgs \
    libgoogle-glog-dev \
    libatlas-base-dev \
    libeigen3-dev \
    libsuitesparse-dev \
    libopencv-dev \
    libboost-dev \
    libboost-filesystem-dev && \
    rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100

RUN sudo git clone https://github.com/ceres-solver/ceres-solver.git && \
    cd ceres-solver && \
    git checkout 1.14.x && \
    sudo mkdir build && \
    cd build && \
    sudo cmake -DCMAKE_BUILD_TYPE=Release .. && \
    sudo make -j$(nproc) && \
    sudo make install && \
    cd ../.. && \
    sudo rm -rf ceres-solver

RUN git clone --branch 2.0.8 https://github.com/18r441m/ethzasl_brisk.git && \
    cd ethzasl_brisk && \
    sudo mkdir build && \
    cd build && \
    sudo cmake -DCMAKE_BUILD_TYPE=Release .. && \
    sudo make -j$(nproc) && \
    sudo make install && \
    cd ../.. && \
    sudo rm -rf ethzasl_brisk

RUN sudo git clone https://github.com/laurentkneip/opengv.git && \
    cd opengv && \
    sudo mkdir build && \
    cd build && \
    sudo cmake .. && \
    sudo make -j$(nproc) && \
    sudo make install

ENV WORKSPACE /svin_ws

RUN mkdir -p /svin_ws/src && \
    cd /svin_ws/src && \
    git clone https://github.com/Mysterium-sch/SVIn.git && \
    cd SVIn &&\
    git checkout test &&\
    cd .. &&\
    git clone https://github.com/AutonomousFieldRoboticsLab/imagenex831l.git && \
    git clone --branch ros-noetic https://github.com/AutonomousFieldRoboticsLab/sonar_rviz_plugin.git

RUN cd /svin_ws/src/SVIn &&\
	rm -r okvis_ros

WORKDIR /svin_ws

