FROM ubuntu:14.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
ENV LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV ROS_DISTRO=indigo

RUN apt -y update && apt -y install locales &&\
    locale-gen en_US en_US.UTF-8 &&\
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

RUN apt -y install software-properties-common &&\
    add-apt-repository universe

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake \
    zip \
    unzip \
    git \
    tmux \
    wget \
    curl \
    vim \
    dpkg \
    build-essential \
    curl &&\
    apt-get -y upgrade &&\
    apt-get -y autoremove

RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -O - | apt-key add -

RUN apt -y update

RUN apt-get -y install ros-indigo-desktop-full python-rosinstall

RUN apt-cache search ros-indigo

RUN rosdep init &&\
    rosdep update

RUN echo "source /opt/ros/indigo/setup.bash" >> ~/.bashrc

