FROM 18r441m/ros:noetic-desktop-full

RUN apt-get update -y &&\
	apt-get install -y --allow-unauthenticated \
	cmake \
	libgoogle-glog-dev \
	git \
	wget \
	zip \
	unzip \
    vim \
	curl \
	dpkg \
	gnupg \
	libomp5-8 \
	libffi-dev \
	lib32z1 \
	software-properties-common \
	freeglut3-dev \
	libjpeg-dev \
	libpng-dev \
	libusb-dev \
	libatomic-ops-dev \
	udev \
	libc6-dev \
	libncursesw5-dev \
	build-essential \
	systemd \
	qtcreator \
	qtbase5-dev \
	qt5-qmake \
	python3-catkin-pkg \
	ros-noetic-catkin &&\
	apt-get -y upgrade &&\
	apt-get -y autoremove

RUN add-apt-repository ppa:ondrej/php
RUN apt-get install -y php7.3

RUN ln -s /usr/lib64/libomp.so /usr/lib64/libomp.so.5

RUN apt-get update && \
    apt-get install -y libqt5gui5 && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://bootstrap.pypa.io/get-pip.py &&\
python3 ./get-pip.py

RUN pip install -U wstool

RUN pip install -U catkin_tools

ENV WORKSPACE /catkin_ws

RUN mkdir -p $WORKSPACE/src &&\
cd $WORKSPACE/src &&\
wstool init &&\
yes y | wstool set ueye_cam --git https://github.com/anqixu/ueye_cam &&\
wstool update

COPY ids-software-suite-linux-64-4.96.1-archive $WORKSPACE/ueye

RUN cd $WORKSPACE/ueye &&\
	yes y | ./ueye_4.96.1.2054_amd64.run

RUN cd $WORKSPACE && \
	catkin init && \
	catkin config --extend /opt/ros/noetic && \
	catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release

RUN	cd $WORKSPACE &&\
	catkin build -j$(nproc)

ENTRYPOINT cd $WORKSPACE &&\
	/bin/bash
