FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
ENV LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV ROS_DISTRO=foxy

RUN apt -y update && apt -y install locales &&\
    locale-gen en_US en_US.UTF-8 &&\
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

RUN apt -y install software-properties-common &&\
    add-apt-repository universe

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake \
    zip \
    unzip \
    git \
    tmux \
    wget \
    curl \
    vim \
    build-essential \
    libfprint-2-2 \
    fprintd \
    libpam-fprintd \
    curl &&\
    apt-get -y upgrade &&\
    apt-get -y autoremove

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
    
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
    
RUN apt -y update && apt full-upgrade && apt-get -y autoremove

RUN dpkg --configure -a

RUN apt -y install ros-foxy-ros-base python3-argcomplete &&\
    apt -y install ros-foxy-desktop python3-argcomplete
    
RUN apt -y install ros-dev-tools

RUN mkdir /catkin_ws

ENTRYPOINT /catkin_ws &&\
	/bin/bash


