%YAML:1.0

#camera calibration 
model_type: PINHOLE
camera_name: cam_fl

#image resize factor. Note that, this factor MUST be same as OKVIS config file
resizeFactor: 1.0

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

fast_relocalization: 1

#loop closure 
#if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
#also give the camera calibration file same as feature_tracker node
loop_closure_params:
    enable: 1  
    min_correspondences: 20
    pnp_reprojection_threshold: 10.0 

health:
    enable: 0
    min_keypoints: 15
    consecutive_keyframes: 3
    keyframe_wait_time: 2.0
    kps_per_quadrant: 1

global_map_params:
    enable: 1
    min_landmark_quality: 0.001

debug_image: 0

image_height: 1200
image_width: 1600
focal_length: [1138.83276975408, 1139.594698074792]
principal_point: [708.1729373830466, 617.1289738266081]
distortion_coefficients: [-0.16289394362063583, 0.08351833356682732, 0.012276483503048642, 0.0006858966792660155]